export const ICONIFY_ICONS = [
  "mdi:account", "mdi:home", "mdi:settings", "mdi:email", "mdi:bell", "mdi:calendar", "mdi:camera", "mdi:cart",
  "mdi:chart-bar", "mdi:check", "mdi:chevron-down", "mdi:chevron-left", "mdi:chevron-right", "mdi:chevron-up",
  "mdi:close", "mdi:cloud", "mdi:cog", "mdi:comment", "mdi:content-copy", "mdi:delete", "mdi:download", "mdi:edit",
  "mdi:eye", "mdi:facebook", "mdi:file", "mdi:filter", "mdi:flag", "mdi:folder", "mdi:github", "mdi:google",
  "mdi:heart", "mdi:help-circle", "mdi:image", "mdi:info", "mdi:instagram", "mdi:layers", "mdi:link", "mdi:list",
  "mdi:lock", "mdi:logout", "mdi:magnify", "mdi:map-marker", "mdi:menu", "mdi:message", "mdi:minus", "mdi:monitor",
  "mdi:music", "mdi:notifications", "mdi:palette", "mdi:pencil", "mdi:phone", "mdi:play", "mdi:plus", "mdi:printer",
  "mdi:refresh", "mdi:rss", "mdi:search", "mdi:send", "mdi:share", "mdi:star", "mdi:tab", "mdi:tag", "mdi:thumb-up",
  "mdi:twitter", "mdi:upload", "mdi:video", "mdi:volume-high", "mdi:wifi", "mdi:window-close", "mdi:youtube",
  "ph:address-book", "ph:airplane", "ph:alarm", "ph:anchor", "ph:apple-logo", "ph:archive", "ph:arrow-down",
  "ph:arrow-left", "ph:arrow-right", "ph:arrow-up", "ph:at", "ph:atom", "ph:backpack", "ph:bank", "ph:barbell",
  "ph:battery-full", "ph:bicycle", "ph:bird", "ph:bluetooth", "ph:boat", "ph:book", "ph:briefcase", "ph:broadcast",
  "ph:browser", "ph:bug", "ph:buildings", "ph:bus", "ph:cactus", "ph:calculator", "ph:calendar-blank", "ph:camera-plus",
  "ph:car", "ph:cardholder", "ph:cat", "ph:chalkboard", "ph:chart-line", "ph:chat", "ph:check-circle", "ph:circle",
  "ph:clipboard", "ph:clock", "ph:cloud-arrow-down", "ph:code", "ph:coffee", "ph:command", "ph:compass", "ph:cookie",
  "ph:cpu", "ph:credit-card", "ph:crown", "ph:cube", "ph:database", "ph:desktop", "ph:detective", "ph:device-mobile",
  "ph:diamond", "ph:dice-five", "ph:dog", "ph:door", "ph:dots-three", "ph:download-simple", "ph:ear", "ph:egg",
  "ph:envelope", "ph:eraser", "ph:eye-slash", "ph:facebook-logo", "ph:fan", "ph:fast-forward", "ph:feather",
  "ph:file-pdf", "ph:fingerprint", "ph:fire", "ph:fish", "ph:flag-banner", "ph:flame", "ph:flash-light", "ph:flask",
  "ph:floppy-disk", "ph:flower", "ph:folder-notched", "ph:football", "ph:fork-knife", "ph:frame-corners", "ph:game-controller",
  "ph:gas-pump", "ph:gauge", "ph:gear", "ph:gift", "ph:git-branch", "ph:github-logo", "ph:globe", "ph:graduation-cap",
  "ph:graph", "ph:grid-four", "ph:hamburger", "ph:hand-pointing", "ph:hard-drive", "ph:hash", "ph:headphones",
  "ph:heart-straight", "ph:hourglass", "ph:house", "ph:ice-cream", "ph:identification-badge", "ph:image-square",
  "ph:infinity", "ph:info-circle", "ph:instagram-logo", "ph:intersect", "ph:jeep", "ph:key", "ph:keyboard",
  "ph:laptop", "ph:leaf", "ph:lego", "ph:lightning", "ph:link-simple", "ph:list-bullets", "ph:lock-laminated",
  "ph:magic-wand", "ph:magnifying-glass", "ph:map-pin", "ph:medal", "ph:medium-logo", "ph:megaphone", "ph:microphone",
  "ph:microsoft-logo", "ph:money", "ph:moon", "ph:mountain", "ph:mouse", "ph:music-note", "ph:newspaper", "ph:notepad",
  "ph:nut", "ph:ny-times", "ph:octagon", "ph:package", "ph:paint-brush", "ph:palette", "ph:paper-plane", "ph:paperclip",
  "ph:password", "ph:path", "ph:pause", "ph:paw-print", "ph:pencil-circle", "ph:phone-call", "ph:phosphor-logo",
  "ph:piano", "ph:picture-in-picture", "ph:pill", "ph:pinterest-logo", "ph:pizza", "ph:placeholder", "ph:planet",
  "ph:play-circle", "ph:playlist", "ph:plug", "ph:plugs", "ph:plus-circle", "ph:poker-chip", "ph:power", "ph:presentation",
  "ph:printer-simple", "ph:prohibit", "ph:projector-screen", "ph:puzzle-piece", "ph:qr-code", "ph:question", "ph:quotes",
  "ph:radio", "ph:radioactive", "ph:rainbow", "ph:receipt", "ph:record", "ph:rectangle", "ph:recycle", "ph:reddit-logo",
  "ph:repeat", "ph:rewind", "ph:robot", "ph:rocket", "ph:rows", "ph:rss-simple", "ph:rug", "ph:ruler", "ph:scales",
  "ph:scissors", "ph:scooter", "ph:screencast", "ph:scribble-loop", "ph:scroll", "ph:selection", "ph:selection-all",
  "ph:selection-background", "ph:selection-foreground", "ph:selection-plus", "ph:selection-slash", "ph:share-network",
  "ph:shield", "ph:shield-check", "ph:shield-plus", "ph:shopping-bag", "ph:shopping-cart", "ph:shovels", "ph:shower",
  "ph:shuffle", "ph:sidebar", "ph:sidebar-simple", "ph:sign-out", "ph:signpost", "ph:sim-card", "ph:sketch-logo",
  "ph:skip-back", "ph:skip-forward", "ph:skull", "ph:slack-logo", "ph:sliders", "ph:smiley", "ph:smiley-blank",
  "ph:smiley-nervous", "ph:smiley-sad", "ph:snow-flake", "ph:speaker-hifi", "ph:speaker-high", "ph:speaker-low",
  "ph:speaker-none", "ph:speaker-slash", "ph:speaker-x", "ph:spinner", "ph:spotify-logo", "ph:square", "ph:square-half",
  "ph:square-logo", "ph:squares-four", "ph:stack", "ph:stack-overflow-logo", "ph:stamp", "ph:star-four", "ph:star-half",
  "ph:sticker", "ph:stop", "ph:stop-circle", "ph:stopwatch", "ph:storefront", "ph:strategy", "ph:stripe-logo",
  "ph:student", "ph:suitcase", "ph:sun", "ph:sun-dim", "ph:swimming-pool", "ph:sword", "ph:t-shirt", "ph:table",
  "ph:tablet", "ph:tag-chevron", "ph:tag-simple", "ph:target", "ph:taxi", "ph:telegram-logo", "ph:television",
  "ph:terminal", "ph:terminal-window", "ph:test-tube", "ph:text-align-center", "ph:text-align-justify",
  "ph:text-align-left", "ph:text-align-right", "ph:text-b-bold", "ph:text-h-one", "ph:text-h-two", "ph:text-h-three",
  "ph:text-h-four", "ph:text-h-five", "ph:text-h-six", "ph:text-indent", "ph:text-italic", "ph:text-outdent",
  "ph:text-strikethrough", "ph:text-t", "ph:text-underline", "ph:thermometer", "ph:thermometer-cold",
  "ph:thermometer-hot", "ph:thumbs-down", "ph:thumbs-up", "ph:ticket", "ph:tiktok-logo", "ph:timer", "ph:toggle-left",
  "ph:toggle-right", "ph:toilet", "ph:toilet-paper", "ph:tote", "ph:train", "ph:train-regional", "ph:train-simple",
  "ph:tram", "ph:translate", "ph:trash", "ph:trash-simple", "ph:tray", "ph:tree", "ph:tree-evergreen", "ph:tree-structure",
  "ph:trend-down", "ph:trend-up", "ph:triangle", "ph:trophy", "ph:truck", "ph:twitch-logo", "ph:twitter-logo",
  "ph:umbrella", "ph:umbrella-simple", "ph:underline-simple", "ph:unite", "ph:upload-simple", "ph:usb", "ph:user",
  "ph:user-circle", "ph:user-circle-gear", "ph:user-circle-plus", "ph:user-gear", "ph:user-minus", "ph:user-plus",
  "ph:user-rectangle", "ph:user-square", "ph:user-switch", "ph:users", "ph:users-four", "ph:users-three", "ph:vibrate",
  "ph:video-camera", "ph:video-camera-slash", "ph:vignette", "ph:vinyl-record", "ph:virtual-reality", "ph:virus",
  "ph:voicemail", "ph:volleyball", "ph:wall", "ph:wallet", "ph:warning", "ph:warning-circle", "ph:warning-octagon",
  "ph:watch", "ph:wave-sawtooth", "ph:wave-sine", "ph:wave-square", "ph:wave-triangle", "ph:waves", "ph:webcam",
  "ph:whatsapp-logo", "ph:wheelchair", "ph:wifi-high", "ph:wifi-low", "ph:wifi-medium", "ph:wifi-none", "ph:wifi-slash",
  "ph:wifi-x", "ph:wind", "ph:windows-logo", "ph:wine", "ph:wrench", "ph:x-circle", "ph:x-square", "ph:yin-yang",
  "ph:youtube-logo"
];
