import { 
  Code2, 
  Braces, 
  Hash, 
  FileJson, 
  Type, 
  Link2, 
  Fingerprint, 
  Globe, 
  FileSpreadsheet, 
  FileType, 
  Key, 
  AlignLeft, 
  Clock, 
  ShieldCheck, 
  Eye,
  Plus,
  Search
} from "lucide-react";
import React from "react";

export type ToolConfig = {
  id: string;
  name: string;
  description: string;
  icon: React.ElementType;
  route: string;
  category: "formatting" | "converters" | "encoding" | "generation" | "security" | "utils";
  metaTitle: string;
  metaDescription: string;
};

export const TOOLS: ToolConfig[] = [
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Beautify and validate your JSON data with history support.",
    icon: FileJson,
    route: "/tools/json-formatter",
    category: "formatting",
    metaTitle: "JSON Formatter | DevHub",
    metaDescription: "Beautify, minify, and validate JSON data instantly in your browser.",
  },
  {
    id: "base64",
    name: "Base64 Tool",
    description: "Encode or decode strings to Base64 format.",
    icon: Hash,
    route: "/tools/base64",
    category: "encoding",
    metaTitle: "Base64 Tool | DevHub",
    metaDescription: "Encode and decode strings to and from Base64 format securely.",
  },
  {
    id: "url-encoder",
    name: "URL Encoder",
    description: "Encode or decode URL components safely.",
    icon: Link2,
    route: "/tools/url-encoder",
    category: "encoding",
    metaTitle: "URL Encoder | DevHub",
    metaDescription: "Safely encode and decode URL components and parameters.",
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode and inspect JSON Web Tokens payloads.",
    icon: Code2,
    route: "/tools/jwt-decoder",
    category: "security",
    metaTitle: "JWT Decoder | DevHub",
    metaDescription: "Inspect and decode JSON Web Tokens (JWT) headers and payloads.",
  },
  {
    id: "uuid-generator",
    name: "UUID Gen",
    description: "Generate v4 UUIDs for your projects.",
    icon: Fingerprint,
    route: "/tools/uuid-generator",
    category: "generation",
    metaTitle: "UUID Generator | DevHub",
    metaDescription: "Generate high-quality v4 UUIDs for your development and database needs.",
  },
  {
    id: "http-status",
    name: "HTTP Status",
    description: "Explore HTTP status codes and their meanings.",
    icon: Globe,
    route: "/tools/http-status",
    category: "utils",
    metaTitle: "HTTP Status Explorer | DevHub",
    metaDescription: "Browse and understand HTTP response status codes and their meanings.",
  },
  {
    id: "csv-json",
    name: "CSV to JSON",
    description: "Convert CSV data to JSON objects and vice versa.",
    icon: FileSpreadsheet,
    route: "/tools/csv-json",
    category: "converters",
    metaTitle: "CSV to JSON Converter | DevHub",
    metaDescription: "Convert CSV data to JSON array format and vice versa instantly.",
  },
  {
    id: "yaml-json",
    name: "YAML to JSON",
    description: "Convert between YAML and JSON formats.",
    icon: FileType,
    route: "/tools/yaml-json",
    category: "converters",
    metaTitle: "YAML to JSON Converter | DevHub",
    metaDescription: "Switch between YAML and JSON formats with preserved structure.",
  },
  {
    id: "password-gen",
    name: "Password Gen",
    description: "Create secure, random passwords instantly.",
    icon: Key,
    route: "/tools/password-generator",
    category: "security",
    metaTitle: "Password Generator | DevHub",
    metaDescription: "Generate secure, random passwords with customizable parameters.",
  },
  {
    id: "lorem-ipsum",
    name: "Lorem Ipsum",
    description: "Generate placeholder text for your designs.",
    icon: AlignLeft,
    route: "/tools/lorem-ipsum",
    category: "generation",
    metaTitle: "Lorem Ipsum Generator | DevHub",
    metaDescription: "Generate placeholder text in words, sentences, or paragraphs.",
  },
  {
    id: "timezone",
    name: "Timezone Tool",
    description: "Convert and compare times across zones.",
    icon: Clock,
    route: "/tools/timezone-converter",
    category: "utils",
    metaTitle: "Timezone Converter | DevHub",
    metaDescription: "Convert and compare times across different global time zones easily.",
  },
  {
    id: "hash-gen",
    name: "Hash Gen",
    description: "Generate MD5, SHA256 hashes for any text.",
    icon: ShieldCheck,
    route: "/tools/hash-generator",
    category: "security",
    metaTitle: "Hash Generator | DevHub",
    metaDescription: "Generate MD5, SHA1, SHA256, and SHA512 hashes for any text input.",
  },
  {
    id: "bcrypt-gen",
    name: "Bcrypt Gen",
    description: "Securely hash passwords using Bcrypt algorithm.",
    icon: ShieldCheck,
    route: "/tools/bcrypt-generator",
    category: "security",
    metaTitle: "Bcrypt Generator | DevHub",
    metaDescription: "Securely hash passwords using the Bcrypt algorithm with adjustable salt rounds.",
  },
  {
    id: "bcrypt-comp",
    name: "Bcrypt Check",
    description: "Verify if a password matches a Bcrypt hash.",
    icon: ShieldCheck,
    route: "/tools/bcrypt-comparator",
    category: "security",
    metaTitle: "Bcrypt Checker | DevHub",
    metaDescription: "Verify and compare plain text passwords against Bcrypt hashes.",
  },
  {
    id: "sql-formatter",
    name: "SQL Format",
    description: "Format and beautify your SQL queries.",
    icon: FileJson,
    route: "/tools/sql-formatter",
    category: "formatting",
    metaTitle: "SQL Formatter | DevHub",
    metaDescription: "Beautify and format SQL queries for better readability and structure.",
  },
  {
    id: "regex-tester",
    name: "Regex Test",
    description: "Test and debug regular expressions.",
    icon: Search,
    route: "/tools/regex-tester",
    category: "utils",
    metaTitle: "Regex Tester | DevHub",
    metaDescription: "Test and debug JavaScript regular expressions with real-time match highlighting.",
  },
  {
    id: "markdown-preview",
    name: "Markdown Pre",
    description: "Write and preview markdown in real-time.",
    icon: Eye,
    route: "/tools/markdown-preview",
    category: "formatting",
    metaTitle: "Markdown Previewer | DevHub",
    metaDescription: "Write and preview GitHub-flavored markdown with live sync.",
  },
];
